from .login_form import LoginForm
from .signup_form import SignUpForm
from .add_portfolio_stock_form import AddPortfolioStockForm
from .create_portfolio_form import CreatePortfolioForm
from .update_portfolio_form import UpdatePortfolioForm
from .update_portfolio_stock_form import UpdatePortfolioStockForm
from .watchlist_form import WatchlistForm
from .watchlist_stock_form import WatchlistStockForm
from .algorithm_form import AlgorithmForm
from .backtest_form import BacktestForm
from .algorithm_block_form import AlgorithmBlockForm
